# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('SP', 'Sport'), ('BS', 'Business'), ('TE', 'Technology'), ('GA', 'Gaming'), ('PO', 'Politics'), ('MU', 'Music')], max_length=2),
        ),
    ]
